import { EntityComponents, SingletonComponent } from "@/common/components";
import { AbilitiesComponent } from "./abilities";
import { ArenaComponent } from "./arena";
import { BodyComponent } from "./body";
import { DetectedCollisionsComponent } from "./detectedcollisions";
import { GameEventsComponent } from "./gameevents";
import { GameStateComponent } from "./gamestate";
import { HealthComponent } from "./health";
import { LifetimeComponent } from "./lifetime";
import { OrderComponent } from "./order";
import { PlayerComponent } from "./player";
import { PlayerOwnedComponent } from "./playerowned";
import { ProjectileComponent } from "./projectile";
import { PullComponent } from "./pull";
import { ShieldComponent } from "./shield";
import { ShopComponent } from "./shop";
import { UnitComponent } from "./unit";

export type GameComponent = {
  shops: EntityComponents<ShopComponent>;
  bodies: EntityComponents<BodyComponent>;
  gameState: SingletonComponent<GameStateComponent>;
  gameEvents: SingletonComponent<GameEventsComponent>;
  healths: EntityComponents<HealthComponent>;
  lifetimes: EntityComponents<LifetimeComponent>;
  playerOwneds: EntityComponents<PlayerOwnedComponent>;
  projectiles: EntityComponents<ProjectileComponent>;
  orders: EntityComponents<OrderComponent>;
  arena: SingletonComponent<ArenaComponent>;
  abilities: EntityComponents<AbilitiesComponent>;
  units: EntityComponents<UnitComponent>;
  shields: EntityComponents<ShieldComponent>;
  players: EntityComponents<PlayerComponent>;
  detectedCollisions: SingletonComponent<DetectedCollisionsComponent>;
  pulls: EntityComponents<PullComponent>;
};
